### PR TITLE
Add seedminer to .stock

### PR DESCRIPTION
**Pull request by PixelSergey**
While 3ds.hacks.guide/seedminer is nonexistant, this is a good alternative
(Getting tired of saying `.stock use one of these OR seedminer!`)

### CODE REVIEW

**Comment by Jisagi** [comment]
**original one:** which involves a cheap dsiware game and an adequately powerful PC (or a friend/helper with one)
**idea:** which involves buying a dsiware game and an adequately powerful PC (GPU or CPU) or a friend with one

**Comment by PixelSergey** [comment]
@Jisagi that sounds like you need to buy the PC (which you, technically, do, but still)

**Comment by Jisagi** [comment]
maybe rather "[...]an adequately powerful GPU or CPU (or a friend with one)"

**Comment by PixelSergey** [comment]
That still sounds like you need to buy a fresh gpu

**Comment by Jisagi** [comment]
> which needs a dsiware game and an adequately powerful GPU or CPU (or a friend with one)
~~last offer~~

**Comment by PixelSergey** [comment]
~~so pretty much how I phrased it in the beginning~~

**Comment by Jisagi** [comment]
better worded and without the "helper" part

**Comment by Jisagi** [comment]
One more thing: we agreed internally to add this as our improved fork.
https://jisagi.github.io/3dsSeedMinerGuide/

**Comment by PixelSergey** [comment]
k

**Pull request merged**
